Boss/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('update_user/', views.updateUser, name='updateUser'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('adminbrands/', views.adminbrands, name='adminbrands'),
    path('admincategory/', views.admincategory, name='admincategory'),
    path('adminproducts/', views.adminproducts, name='adminproducts'),
    path('adminorders/', views.adminorders, name='adminorders'),
    path('admincustomers/', views.admincustomers, name='admincustomers'),
    path('admindashboard/', views.admindashboard, name='admindashboard'),
]

LapTop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop.urls')),
    path('account/', include('Account.urls')),
    # path('boss/', include('Boss.urls')),
    path('checkout/', include('Checkout.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

Shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('store/', views.Store, name='store'),
    path('update_item/', views.updateItem, name='update_item'),
    path('product/<int:id>/', views.product, name='product'),
    path('aboutUS/', views.aboutUs, name='aboutUs'),
    path('contact/', views.contact, name='contact'),
    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('ordersandreturns/', views.ordersandreturns, name='ordersandreturns'),
    path('termandconditions/', views.termandconditions, name='termandconditions'),
    path('help/', views.help, name='help'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.utils.safestring import mark_safe

from Account.models import Customer

class Brand(models.Model):
    brandName = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.brandName


class Category(models.Model):
    categoryName = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.categoryName


class Product(models.Model):
    demand = (
        ('Học tập - Văn phòng', 'Học tập - Văn phòng'),
        ('Đồ họa- Kĩ thuật', 'Đồ họa- Kĩ thuật'),
        ('Gaming', 'Gaming'),
        ('Cao cấp-Sang trọng', 'Cao cấp-Sang trọng'),
    )
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    price = models.PositiveBigIntegerField()
    quantity = models.IntegerField()
    quantitySelled = models.IntegerField(default=0)
    demand = models.CharField(max_length=200, null=True, choices=demand)
    dateAdded = models.DateTimeField(auto_now_add=True)
    Card = models.CharField(max_length=200, null=True)
    Screen = models.CharField(max_length=200, null=True)
    RAM = models.CharField(max_length=200, null=True)
    hard_disk = models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank=True)
    detail = RichTextUploadingField(null=True, blank=True)

    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.name

    def image_tag(self):
        if self.image.url is not None:
            return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
        else:
            return ""


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True)

    def ImageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.product.name


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)

    def get_total_product(self):
        sum = 0;
        cart_product = self.cart_product_set.all()
        for o in cart_product:
            sum = sum + o.quantity;
        return sum

    def get_total_price_product(self):
        sum = 0;
        cart_product = self.cart_product_set.all()
        for o in cart_product:
            sum += o.get_price_product();
        return sum;


class Cart_Product(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)

    def get_price_product(self):
        return int(self.product.price * self.quantity)

Shop/views.py
import json
import datetime

from django.template.loader import render_to_string

from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from .models import *
from .filter import *


# Create your views here.
def Home(request):
    newProduct = Product.objects.order_by('dateAdded')[0:6]
    topSelling = Product.objects.order_by('-quantitySelled')[0:6]
    (cart, cart_product) = Same(request)
    context = {
        'newProduct': newProduct,
        'topSelling': topSelling,
        'cart': cart,
        'cart_product': cart_product,
    }
    return render(request, 'Shop/Home.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    quantity = data['quantity']
    print("quantity", quantity)
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    cart, created = Cart.objects.get_or_create(customer=customer)
    cart_product, created = Cart_Product.objects.get_or_create(cart=cart, product=product)
    if action == 'add' and product.quantity >= int(quantity):
        cart_product.quantity = (cart_product.quantity + int(quantity))
        if cart_product.quantity > product.quantity:
            cart_product.quantity = product.quantity
        cart_product.save()

    elif action == 'remove':
        cart_product.delete()

    return JsonResponse("cart is updated", safe=False)


def Same(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        cart, created = Cart.objects.get_or_create(customer=customer)
        cart_product = cart.cart_product_set.all()

    else:
        cart_product = []
        cart = {'get_total_product': 0, 'get_total_price_product': 0}

    return (cart, cart_product)


def Store(request):
    Allproducts = Product.objects.all()

    myfilter = productFilter(request.GET, queryset=Allproducts)
    Allproducts = myfilter.qs

    search = request.POST.get('myInput')
    if request.method == "POST" and search is not None:
        Allproducts = Product.objects.filter(name__icontains=search)

    if request.method == 'GET' and request.is_ajax():
        print("request:", request)
        data = {}
        myfilter = productFilter(request.GET, queryset=Allproducts.values())
        Allproduct = list(myfilter.qs)
        data['products'] = json.dumps(Allproduct, default=myconverter)
        return JsonResponse(data, status=200)

    paginator = Paginator(Allproducts, 8)
    pagenum = request.GET.get('page', 1)
    numPage = paginator.num_pages  ### get number of page
    (cart, cart_product) = Same(request)

    try:
        products = paginator.page(pagenum)
    except (EmptyPage, InvalidPage, ValueError):
        products = paginator.page(1)
    context = {
        'products': products,
        'numPage': range(1, numPage + 1),
        'cart': cart,
        'cart_product': cart_product,
        'myfilter': myfilter,
        'search': search,
    }
    return render(request, 'Shop/Store.html', context)


def myconverter(obj):
    if isinstance(obj, (datetime.date, datetime.datetime)):
        return obj.isoformat()


def product(request, id):
    productid = get_object_or_404(Product, pk=id)
    productRelate = Product.objects.filter(brand=productid.brand)[0:4]
    (cart, cart_product) = Same(request)
    images = Images.objects.filter(product_id=id)
    context = {
        'product': productid,
        'productRelate': productRelate,
        'images': images,
        'cart': cart,
        'cart_product': cart_product,
    }
    return render(request, 'Shop/product.html', context)


def aboutUs(request):
    (cart, cart_product) = Same(request)
    return render(request, 'Shop/aboutUS.html', {'cart': cart, 'cart_product': cart_product})


# def contact(request):
#     return render(request, 'Shop/contact.html')

def contact(request):
    (cart, cart_product) = Same(request)
    if request.method == 'POST':
        subject = 'Subject here',
        message = 'Here is the message.',
        email_from = settings.EMAIL_HOST_USER,
        recipient_list = [request.POST.get('email_receive')],
        email_template_name = "Shop/mailContact.txt",
        email = render_to_string(email_template_name)
        send_mail(
            'Thông tin khuyến mãi',
            email,
            settings.EMAIL_HOST_USER,
            recipient_list[0],
        )
        messages.success(request, "Email của bạn đã được gửi thông tin"),
    else:
        messages.warning(request, "Mời nhập email")
    return render(request, 'Shop/contact.html', {'cart': cart, 'cart_product': cart_product})


def privacypolicy(request):
    (cart, cart_product) = Same(request)
    return render(request, 'Shop/privacypolicy.html', {'cart': cart, 'cart_product': cart_product})


def ordersandreturns(request):
    (cart, cart_product) = Same(request)
    return render(request, 'Shop/ordersandreturns.html', {'cart': cart, 'cart_product': cart_product})


def termandconditions(request):
    (cart, cart_product) = Same(request)
    return render(request, 'Shop/termsandconditions.html', {'cart': cart, 'cart_product': cart_product})


def help(request):
    (cart, cart_product) = Same(request)
    return render(request, 'Shop/help.html', {'cart': cart, 'cart_product': cart_product})

Shop/templates/Shop/Home.html
{% extends 'Shop/main.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% block content %}
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li class="active"><a href="{% url 'home' %}">Trang chủ</a></li>
                <li><a href="{% url 'store' %}">Cửa hàng</a></li>
                <li><a href="{% url 'aboutUs' %}">Chúng tôi</a></li>
                <li><a href="{% url 'contact' %}">Liên hệ</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<div class="section">

    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- shop -->

            <div class="col-md-3 col-xs-6">
                <div class="shop">
                    <div class="shop-img">
                        <img src="{% static './img/gaming.jpg' %}" alt="">
                    </div>
                    <div class="shop-body">
                        <h4>Laptop<br>Học tập - Văn phòng</h4>
                        <a href="{% url 'store' %}?demand=Học%20tập%20-%20Văn%20phòng" class="cta-btn">Shop now <i
                                class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-6">
                <div class="shop">
                    <div class="shop-img">
                        <img src="{% static './img/gaming.jpg' %}" alt="">
                    </div>
                    <div class="shop-body">
                        <h4 style="padding-bottom: 18px;">Laptop<br>Gaming</h4>
                        <a href="{% url 'store' %}?demand=Gaming" class="cta-btn">Shop now <i
                                class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-6">
                <div class="shop">
                    <div class="shop-img">
                        <img src="{% static './img/gaming.jpg' %}" alt="">
                    </div>
                    <div class="shop-body">
                        <h4>Laptop<br>Đồ họa- Kĩ thuật</h4>
                        <a href="{% url 'store' %}?demand=Đồ họa- Kĩ thuật" class="cta-btn">Shop now <i
                                class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-6">
                <div class="shop">
                    <div class="shop-img">
                        <img src="{% static './img/gaming.jpg' %}" alt="">
                    </div>
                    <div class="shop-body">
                        <h4>Laptop<br>Cao cấp-Sang trọng</h4>
                        <a href="{% url 'store' %}?demand=Cao cấp-Sang trọng" class="cta-btn">Shop now <i
                                class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>

            <!-- /shop -->


            <!-- /shop -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>


<!-- ******************************* New Product *********************** -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="section-title">
                    <h3 class="title">Sản phẩm mới </h3>
                </div>
            </div>
            <!-- Products tab & slick -->
            <div class="col-md-12">
                <div class="row">
                    <div class="products-tabs">
                        <!-- tab -->
                        <div id="tab1" class="tab-pane active">
                            <div class="products-slick" data-nav="#slick-nav-1">
                                <!-- product -->
                                {% for product in newProduct %}
                                <div class="product">
                                    <a href="{% url 'product' product.id %}">
                                        <div class="product-img">
                                            <img src="{{product.ImageURL}}" alt="">
                                            <div class="product-label">
                                            </div>
                                        </div>
                                    </a>
                                    <div class="product-body">
                                        <p class="product-category">{{product.demand}}</p>
                                        <h3 class="product-name"><a href="{% url 'product' product.id %}">{{product.name}}</a>
                                        </h3>
                                        <h4 class="product-price">{{product.price|intcomma}},000 Vnd</h4>
                                        <!--												<div class="product-rating">-->

                                        <!--												</div>-->
                                        <!--												<div class="product-btns">-->
                                        <!--													<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>-->
                                        <!--												</div>-->
                                    </div>
                                    <div class="add-to-cart">
                                        <button data-product={{product.id}} data-action="add"
                                                class="add-to-cart-btn update-cart"><i class="fa fa-shopping-cart"></i>
                                            Thêm vào giỏ hàng
                                        </button>
                                    </div>
                                </div>
                                <!-- /product -->
                                {% endfor %}


                                <!-- /product -->
                            </div>
                            <div id="slick-nav-1" class="products-slick-nav"></div>
                        </div>
                        <!-- /tab -->
                    </div>
                </div>
            </div>
            <!-- Products tab & slick -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>


<!-- ******************************* Top selling *********************** -->

<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <!-- section title -->
            <div class="col-md-12">
                <div class="section-title">
                    <h3 class="title">Top selling</h3>
                    <div class="section-nav">

                    </div>
                </div>
            </div>
            <!-- /section title -->

            <!-- Products tab & slick -->
            <div class="col-md-12" style="margin-bottom:35px">
                <div class="row">
                    <div class="products-tabs">
                        <!-- tab -->
                        <div id="tab2" class="tab-pane fade in active">
                            <div class="products-slick" data-nav="#slick-nav-2">
                                <!-- product -->
                                {% for product in topSelling %}
                                <div class="product">
                                    <div class="product-img">
                                        <img src="{{product.ImageURL}}" alt="">
                                        <div class="product-label">
                                        </div>
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">{{product.demand}}</p>
                                        <h3 class="product-name"><a href="{% url 'product' product.id %}">{{product.name}}</a>
                                        </h3>
                                        <h4 class="product-price">{{product.price|intcomma}},000 Vnd</h4>
                                        <!--												<div class="product-rating">-->
                                        <!--													-->
                                        <!--												</div>-->
                                        <!--												<div class="product-btns">-->
                                        <!--													<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>-->
                                        <!--												</div>-->
                                    </div>
                                    <div class="add-to-cart">
                                        <button data-product={{product.id}} data-action="add"
                                                class="add-to-cart-btn update-cart"><i class="fa fa-shopping-cart"></i>Thêm
                                            vào giỏ hàng
                                        </button>
                                    </div>
                                </div>
                                <!-- /product -->
                                {% endfor %}

                                <!-- /product -->
                            </div>
                            <div id="slick-nav-2" class="products-slick-nav"></div>
                        </div>
                        <!-- /tab -->
                    </div>
                </div>
            </div>
            <!-- /Products tab & slick -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>


{% endblock content %}

Shop/templates/Shop/Store.html
{% extends 'Shop/main.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% block content %}
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li><a href="{% url 'home' %}">Trang chủ</a></li>
                <li class="active"><a href="{% url 'store' %}">Cửa hàng</a></li>
                <li><a href="{% url 'aboutUs' %}">Chúng tôi</a></li>
                <li><a href="{% url 'contact' %}">Liên hệ</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- ASIDE -->
            <!-- /ASIDE -->

            <!-- STORE -->
            <div id="store" class="col-md-12">
                <!-- store fillter -->
                <div class="store-filter clearfix">
                    <div class="store-sort">
                        <form id="formSearch">
                            <label>
                                <label>Demand: &nbsp {% render_field myfilter.form.demand class="input-select" %}
                                    &nbsp</label>
                                <label>Category: &nbsp {% render_field myfilter.form.category class="input-select" %}
                                    &nbsp</label>
                                <label>Brand: &nbsp {% render_field myfilter.form.brand class="input-select" %}</label>
                            </label>
                            Price:
                            <select class="input-select" id="id_price">
                                <option value="0">-----------</option>
                                <option value="1">Dưới 10 triệu</option>
                                <option value="2">10 triệu - 20 triệu</option>
                                <option value="3">20 triệu - 30 triệu</option>
                                <option value="4">Trên 30 triệu</option>

                            </select>
                        </form>

                    </div>

                </div>
                <!-- /store fillter -->
                <!-- store products -->
                <div class="row" id="id_row">
                    <!-- product -->
                    {% for product in products %}
                    <div class="col-md-3 col-xs-4">
                        <div class="product">
                            <a href="{% url 'product' product.id %}">
                                <div class="product-img">

                                    <img src="{{product.ImageURL}}" alt="" style="width: 100%">
                                </div>
                            </a>
                            <div class="product-body">
                                <p class="product-category">{{product.demand}}</p>
                                <h3 class="product-name"><a href="{% url 'product' product.id %}">{{product.name}}</a>
                                </h3>
                                <h4 class="product-price">{{product.price|intcomma}},000 Vnd</h4>
                                <!--									<div class="product-rating">-->

                                <!--									</div>-->
                                <!--									<div class="product-btns">-->
                                <!--										<a class="quick-view"><i class="fa fa-eye"></i></a>-->
                                <!--									</div>-->
                                <div class="quick-information">
                                    <p>name</p>
                                    <p>config</p>
                                    <p>ram</p>
                                    <p>disk</p>
                                </div>
                            </div>
                            <div class="add-to-cart">
                                <button data-product={{product.id}} data-action="add"
                                        class="add-to-cart-btn update-cart"><i class="fa fa-shopping-cart"></i> Thêm vào giỏ hàng
                                </button>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <!-- /store products -->

                <!-- store bottom filter -->

                <div class="store-filter clearfix">

                    <ul class="store-pagination">
                        {% if products.has_previous %}
                        <li><a href="?page={{ products.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
                        </li>
                        {% if products.number|add:'-1' > 1 %}
                        <li><a href="?page={{ products.number|add:'-1' }}">&hellip;</a></li>
                        {% endif %}
                        {% endif%}


                        {% for i in numPage %}
                        {% if products.number == i %}
                        <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                        {% elif i > products.number|add:'-2' and i < products.number|add:'2' %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endif %}

                        {% endfor%}


                        {% if products.has_next %}

                        {% if products.number|add:'1' > 1 %}
                        <li><a href="?page={{ products.number|add:'-1' }}">&hellip;</a></li>
                        {% endif %}
                        <li><a href="?page={{ products.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                        {% endif%}
                    </ul>
                </div>
                <!-- /store bottom filter -->
            </div>
            <!-- /STORE -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>


{% endblock content %}

Shop/templates/Shop/help.html
{% extends 'Shop/main.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% block content %}
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li><a href="{% url 'home' %}">Trang chủ</a></li>
                <li><a href="{% url 'store' %}">Cửa hàng</a></li>
                <li class="active"><a href="{% url 'aboutUs' %}">Chúng tôi</a></li>
                <li><a href="{% url 'contact' %}">Liên hệ</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<br>
<br>
<div style="margin-left: 20%; margin-right: 20%">
    <br>
    <h1 style="margin-left: 35%">GIÚP ĐỠ</h1>
    <br>
    <br>

    <p>Chúng tôi muốn xây dựng cộng đồng LapShop thân thiện và tích cực! Tiêu chuẩn này được đưa ra để hướng dẫn người
        bán và người mua gìn giữ một thị trường mua bán an toàn. Vui lòng đọc những việc nên và không nên làm dưới đây
        khi sử dụng ứng dụng Shopee. Bằng việc dùng ứng dụng này, bạn đồng ý với các Điều khoản sử dụng của chúng tôi.
        Chúng tôi cam kết nỗ lực gìn giữ sự an toàn cho cộng đồng mua bán này.</p>

    <p></p>

    <p>Người mua sẽ chú ý ngay nếu sản phẩm của bạn có ảnh hấp dẫn. Để có những bức ảnh thật đẹp, bạn có thể tham khảo
        Mẹo bán hàng trên LapShop. Bên cạnh đó, hãy là người bán hàng chân thật, mô tả sản phẩm thật chính xác và chi
        tiết vì khách hàng luôn muốn biết rõ về sản phẩm mà họ mua. Nhờ đó, bạn sẽ nhận được những đánh giá tích cực từ
        họ!</p>

    <p></p>

    <p>Chúng tôi muốn xây dựng một cộng đồng an toàn và văn minh để mọi người cùng tận hưởng niềm vui mua sắm trên di
        động. Vì vậy, hãy đăng tải những nội dung lành mạnh và phù hợp với tất cả mọi người; không sử dụng ngôn ngữ thô
        tục, đăng các nội dung xấu hay làm phiền người khác. Trong cộng đồng LapShop, người dùng phải tôn trọng lẫn nhau
        và cư xử có thiện chí giữa người mua và người bán, cũng như giữa người dùng và LapShop. Dù bạn mua hay bán hàng
        trên LapShop, hãy tuân thủ những quy tắc dưới đây để đảm bảo mọi người cùng được mua sắm dễ dàng!</p>

    <p></p>

    <br>
    <br>
</div>

{% endblock content %}